2018/08/21 10:11:17 [error] 9#9: *83 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:11:17 [error] 9#9: *85 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:14:42 [error] 9#9: *87 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:14:42 [error] 9#9: *89 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:16:19 [error] 9#9: *91 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:16:19 [error] 9#9: *93 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:21:02 [error] 9#9: *97 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:21:02 [error] 9#9: *99 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:21:46 [error] 9#9: *101 connect() failed (113: No route to host) while connecting to upstream, client: 172.24.0.1, server: sf4.test, request: "GET /pizza/ HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "sf4.test:8080"
2018/08/21 10:22:09 [error] 9#9: *101 connect() failed (113: No route to host) while connecting to upstream, client: 172.24.0.1, server: sf4.test, request: "GET /pizza/ HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "sf4.test:8080"
2018/08/21 10:28:18 [error] 8#8: *47 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:28:18 [error] 8#8: *49 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:28:58 [error] 8#8: *53 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:28:58 [error] 8#8: *55 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:30:54 [error] 9#9: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:30:54 [error] 9#9: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:37:28 [error] 9#9: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:37:28 [error] 9#9: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:37:48 [error] 9#9: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:37:48 [error] 9#9: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:39:16 [error] 8#8: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:39:16 [error] 8#8: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:44:38 [error] 8#8: *11 connect() failed (113: No route to host) while connecting to upstream, client: 172.24.0.1, server: sf4.test, request: "GET /pizza/ HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "sf4.test:8080"
2018/08/21 10:47:58 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:47:58 [error] 8#8: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:49:46 [error] 8#8: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:49:46 [error] 8#8: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:54:58 [error] 8#8: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 10:54:58 [error] 8#8: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 11:00:24 [error] 10#10: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 11:00:24 [error] 10#10: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 11:05:16 [error] 10#10: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 11:05:16 [error] 10#10: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 11:27:42 [error] 10#10: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 11:27:42 [error] 10#10: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 11:36:35 [error] 9#9: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 11:36:35 [error] 9#9: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 11:38:03 [error] 9#9: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /ingredient HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 11:38:03 [error] 9#9: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 11:44:56 [error] 9#9: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /ingredient HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 11:44:56 [error] 9#9: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 11:45:47 [error] 9#9: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /ingredient HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 11:45:47 [error] 9#9: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 11:46:29 [error] 9#9: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /ingredient HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 11:46:29 [error] 9#9: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 11:51:46 [error] 9#9: *21 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /ingredient HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 11:51:46 [error] 9#9: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 11:53:12 [error] 9#9: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /ingredient HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 11:53:12 [error] 9#9: *27 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 11:56:43 [error] 8#8: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /ingredient HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 11:56:43 [error] 8#8: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 12:08:10 [error] 8#8: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /ingredient HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 12:08:10 [error] 8#8: *27 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 12:08:53 [error] 8#8: *29 connect() failed (113: No route to host) while connecting to upstream, client: 172.24.0.1, server: sf4.test, request: "GET /pizza/ HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "sf4.test:8080", referrer: "http://sf4.test:8080/pizza/new"
2018/08/21 12:22:29 [error] 8#8: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /ingredient HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 12:22:29 [error] 8#8: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 12:25:33 [error] 8#8: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/21 12:26:24 [error] 8#8: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: localhost, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/22 06:12:13 [error] 8#8: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.2, server: 0.0.0.0, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/22 06:12:52 [error] 8#8: *13 connect() failed (113: No route to host) while connecting to upstream, client: 172.24.0.1, server: sf4.test, request: "GET /pizza/ HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "sf4.test:8080", referrer: "http://sf4.test:8080/pizza/new"
2018/08/22 06:16:45 [error] 8#8: *15 connect() failed (113: No route to host) while connecting to upstream, client: 172.24.0.1, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "localhost:8080"
2018/08/22 06:17:48 [error] 8#8: *17 connect() failed (113: No route to host) while connecting to upstream, client: 172.24.0.1, server: 0.0.0.0, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/22 06:19:59 [error] 8#8: *19 connect() failed (113: No route to host) while connecting to upstream, client: 172.24.0.1, server: 0.0.0.0, request: "GET /pizza HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/22 07:13:10 [error] 9#9: *2 connect() failed (113: No route to host) while connecting to upstream, client: 172.24.0.1, server: sf4.test, request: "GET /pizza/ HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "sf4.test:8080", referrer: "http://sf4.test:8080/pizza/new"
2018/08/22 07:25:50 [error] 9#9: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "localhost:8080"
2018/08/22 07:25:50 [error] 9#9: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "localhost:8080"
2018/08/22 07:25:50 [error] 9#9: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "localhost:8080"
2018/08/22 07:26:00 [error] 9#9: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/22 07:26:00 [error] 9#9: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "172.24.0.3"
2018/08/22 07:29:49 [error] 9#9: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: sf4.test, request: "GET /pizza/ HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "sf4.test:8080", referrer: "http://sf4.test:8080/pizza/new"
2018/08/22 07:29:50 [error] 9#9: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: sf4.test, request: "GET /pizza/ HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "sf4.test:8080", referrer: "http://sf4.test:8080/pizza/new"
2018/08/22 07:29:51 [error] 9#9: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: sf4.test, request: "GET /pizza/ HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "sf4.test:8080", referrer: "http://sf4.test:8080/pizza/new"
2018/08/22 07:34:14 [error] 8#8: *13 connect() failed (113: No route to host) while connecting to upstream, client: 172.24.0.1, server: sf4.test, request: "GET /pizza/ HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "sf4.test:8080", referrer: "http://sf4.test:8080/pizza/new"
2018/08/22 07:42:46 [error] 8#8: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: sf4.test, request: "GET /pizza/ HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "sf4.test:8080", referrer: "http://sf4.test:8080/pizza/new"
2018/08/22 07:43:25 [error] 8#8: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: sf4.test, request: "GET / HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "sf4.test:8080"
2018/08/22 09:08:11 [error] 7#7: *22 connect() failed (113: No route to host) while connecting to upstream, client: 172.18.0.1, server: sf4.test, request: "GET /pizza/ HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "sf4.test:8080"
2018/08/27 11:53:13 [error] 7#7: *99 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot declare class Itv\Infrastructure\Event\DomainEventPublisher, because the name is already in use in /var/www/holimana/src/Holimana/Infrastructure/Event/DomainEventPublisher.php on line 10" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/ HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080"
2018/08/27 11:54:49 [error] 7#7: *105 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot use Holimana\Domain\User\UserCollection as UserCollection because the name is already in use in /var/www/holimana/src/Holimana/Application/Command/User/ListUsersHandler.php on line 11" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/ HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080"
2018/08/27 12:00:42 [error] 7#7: *110 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class Holimana\Infrastructure\Persistence\Doctrine\Repository\DoctrineUserRepository contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Holimana\Infrastructure\Persistence\Doctrine\Repository\DoctrineRepository::getCollectionClass) in /var/www/holimana/src/Holimana/Infrastructure/Persistence/Doctrine/Repository/DoctrineUserRepository.php on line 18" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/ HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080"
2018/08/28 06:01:47 [error] 7#7: *177 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function id() on string in /var/www/holimana/src/Holimana/Infrastructure/Persistence/Doctrine/Type/DoctrineUserId.php:19
Stack trace:
#0 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(149): Holimana\Infrastructure\Persistence\Doctrine\Type\DoctrineUserId->convertToDatabaseValue('1', Object(Doctrine\DBAL\Platforms\MySQL57Platform))
#1 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(125): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQuery('default', Array)
#2 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(62): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQueries('default', Array)
#3 /var/www/holimana/vendor/doctrine/doctrine-bundle/DataCollector/DoctrineDataCollector.php(42): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCo" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/1/edit HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080", referrer: "http://holimana.test:8080/user/"
2018/08/28 06:12:00 [error] 7#7: *183 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function id() on string in /var/www/holimana/src/Holimana/Infrastructure/Persistence/Doctrine/Type/DoctrineUserId.php:19
Stack trace:
#0 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(149): Holimana\Infrastructure\Persistence\Doctrine\Type\DoctrineUserId->convertToDatabaseValue('1', Object(Doctrine\DBAL\Platforms\MySQL57Platform))
#1 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(125): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQuery('default', Array)
#2 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(62): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQueries('default', Array)
#3 /var/www/holimana/vendor/doctrine/doctrine-bundle/DataCollector/DoctrineDataCollector.php(42): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCo" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/1/edit HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080", referrer: "http://holimana.test:8080/user/"
2018/08/28 06:14:57 [error] 7#7: *185 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function id() on string in /var/www/holimana/src/Holimana/Infrastructure/Persistence/Doctrine/Type/DoctrineUserId.php:19
Stack trace:
#0 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(149): Holimana\Infrastructure\Persistence\Doctrine\Type\DoctrineUserId->convertToDatabaseValue('1', Object(Doctrine\DBAL\Platforms\MySQL57Platform))
#1 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(125): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQuery('default', Array)
#2 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(62): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQueries('default', Array)
#3 /var/www/holimana/vendor/doctrine/doctrine-bundle/DataCollector/DoctrineDataCollector.php(42): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCo" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/1/edit HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080"
2018/08/28 06:30:35 [error] 7#7: *193 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function id() on string in /var/www/holimana/src/Holimana/Infrastructure/Persistence/Doctrine/Type/DoctrineUserId.php:19
Stack trace:
#0 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(149): Holimana\Infrastructure\Persistence\Doctrine\Type\DoctrineUserId->convertToDatabaseValue('2', Object(Doctrine\DBAL\Platforms\MySQL57Platform))
#1 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(125): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQuery('default', Array)
#2 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(62): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQueries('default', Array)
#3 /var/www/holimana/vendor/doctrine/doctrine-bundle/DataCollector/DoctrineDataCollector.php(42): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCo" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/2 HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080", referrer: "http://holimana.test:8080/user/"
2018/08/28 06:31:00 [error] 7#7: *193 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function id() on string in /var/www/holimana/src/Holimana/Infrastructure/Persistence/Doctrine/Type/DoctrineUserId.php:19
Stack trace:
#0 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(149): Holimana\Infrastructure\Persistence\Doctrine\Type\DoctrineUserId->convertToDatabaseValue('2', Object(Doctrine\DBAL\Platforms\MySQL57Platform))
#1 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(125): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQuery('default', Array)
#2 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(62): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQueries('default', Array)
#3 /var/www/holimana/vendor/doctrine/doctrine-bundle/DataCollector/DoctrineDataCollector.php(42): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCo" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/2/edit HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080", referrer: "http://holimana.test:8080/user/"
2018/08/28 06:31:15 [error] 7#7: *193 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function id() on string in /var/www/holimana/src/Holimana/Infrastructure/Persistence/Doctrine/Type/DoctrineUserId.php:19
Stack trace:
#0 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(149): Holimana\Infrastructure\Persistence\Doctrine\Type\DoctrineUserId->convertToDatabaseValue('2', Object(Doctrine\DBAL\Platforms\MySQL57Platform))
#1 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(125): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQuery('default', Array)
#2 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(62): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQueries('default', Array)
#3 /var/www/holimana/vendor/doctrine/doctrine-bundle/DataCollector/DoctrineDataCollector.php(42): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCo" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/2 HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080", referrer: "http://holimana.test:8080/user/"
2018/08/28 06:34:29 [error] 7#7: *202 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function id() on string in /var/www/holimana/src/Holimana/Infrastructure/Persistence/Doctrine/Type/DoctrineUserId.php:19
Stack trace:
#0 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(149): Holimana\Infrastructure\Persistence\Doctrine\Type\DoctrineUserId->convertToDatabaseValue('2', Object(Doctrine\DBAL\Platforms\MySQL57Platform))
#1 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(125): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQuery('default', Array)
#2 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(62): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQueries('default', Array)
#3 /var/www/holimana/vendor/doctrine/doctrine-bundle/DataCollector/DoctrineDataCollector.php(42): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCo" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/2 HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080", referrer: "http://holimana.test:8080/user/"
2018/08/28 06:35:30 [error] 7#7: *204 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function id() on string in /var/www/holimana/src/Holimana/Infrastructure/Persistence/Doctrine/Type/DoctrineUserId.php:19
Stack trace:
#0 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(149): Holimana\Infrastructure\Persistence\Doctrine\Type\DoctrineUserId->convertToDatabaseValue('2', Object(Doctrine\DBAL\Platforms\MySQL57Platform))
#1 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(125): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQuery('default', Array)
#2 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(62): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQueries('default', Array)
#3 /var/www/holimana/vendor/doctrine/doctrine-bundle/DataCollector/DoctrineDataCollector.php(42): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCo" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/2 HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080", referrer: "http://holimana.test:8080/user/"
2018/08/28 06:38:28 [error] 7#7: *208 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Access level to Holimana\Domain\User\User::$id must be protected (as in class Holimana\Domain\Entity) or weaker in /var/www/holimana/src/Holimana/Domain/User/User.php on line 8" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/2 HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080", referrer: "http://holimana.test:8080/user/"
2018/08/28 06:40:12 [error] 7#7: *210 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function id() on string in /var/www/holimana/src/Holimana/Infrastructure/Persistence/Doctrine/Type/DoctrineUserId.php:19
Stack trace:
#0 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(149): Holimana\Infrastructure\Persistence\Doctrine\Type\DoctrineUserId->convertToDatabaseValue('2', Object(Doctrine\DBAL\Platforms\MySQL57Platform))
#1 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(125): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQuery('default', Array)
#2 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(62): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQueries('default', Array)
#3 /var/www/holimana/vendor/doctrine/doctrine-bundle/DataCollector/DoctrineDataCollector.php(42): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCo" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/2 HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080", referrer: "http://holimana.test:8080/user/"
2018/08/28 06:41:47 [error] 7#7: *212 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function id() on string in /var/www/holimana/src/Holimana/Infrastructure/Persistence/Doctrine/Type/DoctrineUserId.php:19
Stack trace:
#0 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(149): Holimana\Infrastructure\Persistence\Doctrine\Type\DoctrineUserId->convertToDatabaseValue('2', Object(Doctrine\DBAL\Platforms\MySQL57Platform))
#1 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(125): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQuery('default', Array)
#2 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(62): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQueries('default', Array)
#3 /var/www/holimana/vendor/doctrine/doctrine-bundle/DataCollector/DoctrineDataCollector.php(42): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCo" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/2 HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080", referrer: "http://holimana.test:8080/user/"
2018/08/28 06:48:28 [error] 7#7: *214 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function id() on string in /var/www/holimana/src/Holimana/Infrastructure/Persistence/Doctrine/Type/DoctrineUserId.php:19
Stack trace:
#0 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(149): Holimana\Infrastructure\Persistence\Doctrine\Type\DoctrineUserId->convertToDatabaseValue('2', Object(Doctrine\DBAL\Platforms\MySQL57Platform))
#1 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(125): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQuery('default', Array)
#2 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(62): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQueries('default', Array)
#3 /var/www/holimana/vendor/doctrine/doctrine-bundle/DataCollector/DoctrineDataCollector.php(42): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCo" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/2 HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080"
2018/08/28 06:48:36 [error] 7#7: *214 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function id() on string in /var/www/holimana/src/Holimana/Infrastructure/Persistence/Doctrine/Type/DoctrineUserId.php:19
Stack trace:
#0 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(149): Holimana\Infrastructure\Persistence\Doctrine\Type\DoctrineUserId->convertToDatabaseValue('2', Object(Doctrine\DBAL\Platforms\MySQL57Platform))
#1 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(125): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQuery('default', Array)
#2 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(62): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQueries('default', Array)
#3 /var/www/holimana/vendor/doctrine/doctrine-bundle/DataCollector/DoctrineDataCollector.php(42): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCo" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/2 HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080", referrer: "http://holimana.test:8080/user/"
2018/08/28 06:48:52 [error] 7#7: *219 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function id() on string in /var/www/holimana/src/Holimana/Infrastructure/Persistence/Doctrine/Type/DoctrineUserId.php:19
Stack trace:
#0 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(149): Holimana\Infrastructure\Persistence\Doctrine\Type\DoctrineUserId->convertToDatabaseValue('2', Object(Doctrine\DBAL\Platforms\MySQL57Platform))
#1 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(125): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQuery('default', Array)
#2 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(62): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQueries('default', Array)
#3 /var/www/holimana/vendor/doctrine/doctrine-bundle/DataCollector/DoctrineDataCollector.php(42): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCo" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/2 HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080", referrer: "http://holimana.test:8080/user/"
2018/08/28 06:50:28 [error] 7#7: *226 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function id() on string in /var/www/holimana/src/Holimana/Infrastructure/Persistence/Doctrine/Type/DoctrineUserId.php:19
Stack trace:
#0 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(149): Holimana\Infrastructure\Persistence\Doctrine\Type\DoctrineUserId->convertToDatabaseValue('2', Object(Doctrine\DBAL\Platforms\MySQL57Platform))
#1 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(125): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQuery('default', Array)
#2 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(62): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQueries('default', Array)
#3 /var/www/holimana/vendor/doctrine/doctrine-bundle/DataCollector/DoctrineDataCollector.php(42): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCo" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/2 HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080", referrer: "http://holimana.test:8080/user/"
2018/08/28 06:52:33 [error] 7#7: *248 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function id() on string in /var/www/holimana/src/Holimana/Infrastructure/Persistence/Doctrine/Type/DoctrineUserId.php:19
Stack trace:
#0 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(149): Holimana\Infrastructure\Persistence\Doctrine\Type\DoctrineUserId->convertToDatabaseValue('2', Object(Doctrine\DBAL\Platforms\MySQL57Platform))
#1 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(125): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQuery('default', Array)
#2 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(62): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQueries('default', Array)
#3 /var/www/holimana/vendor/doctrine/doctrine-bundle/DataCollector/DoctrineDataCollector.php(42): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCo" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/2 HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080", referrer: "http://holimana.test:8080/user/"
2018/08/28 08:08:01 [error] 7#7: *291 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function id() on string in /var/www/holimana/src/Holimana/Infrastructure/Persistence/Doctrine/Type/DoctrineUserId.php:19
Stack trace:
#0 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(149): Holimana\Infrastructure\Persistence\Doctrine\Type\DoctrineUserId->convertToDatabaseValue('1', Object(Doctrine\DBAL\Platforms\MySQL57Platform))
#1 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(125): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQuery('default', Array)
#2 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(62): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQueries('default', Array)
#3 /var/www/holimana/vendor/doctrine/doctrine-bundle/DataCollector/DoctrineDataCollector.php(42): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCo" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/1/edit HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080", referrer: "http://holimana.test:8080/user/"
2018/08/28 08:08:45 [error] 7#7: *293 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function id() on string in /var/www/holimana/src/Holimana/Infrastructure/Persistence/Doctrine/Type/DoctrineUserId.php:19
Stack trace:
#0 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(149): Holimana\Infrastructure\Persistence\Doctrine\Type\DoctrineUserId->convertToDatabaseValue('1', Object(Doctrine\DBAL\Platforms\MySQL57Platform))
#1 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(125): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQuery('default', Array)
#2 /var/www/holimana/vendor/symfony/doctrine-bridge/DataCollector/DoctrineDataCollector.php(62): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector->sanitizeQueries('default', Array)
#3 /var/www/holimana/vendor/doctrine/doctrine-bundle/DataCollector/DoctrineDataCollector.php(42): Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCo" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/1/edit HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080", referrer: "http://holimana.test:8080/user/"
2018/08/28 11:05:48 [error] 7#7: *443 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Access level to Holimana\Infrastructure\Persistence\Doctrine\Repository\DoctrineRepository::update() must be public (as in class Holimana\Domain\User\UserRepository) in /var/www/holimana/src/Holimana/Infrastructure/Persistence/Doctrine/Repository/DoctrineUserRepository.php on line 18" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/ HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080", referrer: "http://holimana.test:8080/user/efe904cb-bb0d-41a2-9648-cc946422e081/edit"
2018/08/28 11:19:17 [error] 7#7: *447 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of Holimana\Infrastructure\Persistence\Doctrine\Repository\DoctrineRepository::update(Holimana\Domain\Entity $entity) must be compatible with Holimana\Domain\User\UserRepository::update(Holimana\Domain\User\User $user) in /var/www/holimana/src/Holimana/Infrastructure/Persistence/Doctrine/Repository/DoctrineUserRepository.php on line 18" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/ HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080", referrer: "http://holimana.test:8080/user/efe904cb-bb0d-41a2-9648-cc946422e081/edit"
2018/08/28 12:15:31 [error] 7#7: *479 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot declare class Holimana\Application\Command\User\UpdateUserHandler, because the name is already in use in /var/www/holimana/src/Holimana/Application/Command/User/CreateUserHandler.php on line 0" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/ HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080", referrer: "http://holimana.test:8080/user/1/edit"
2018/08/30 12:21:37 [error] 7#7: *733 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected ';', expecting ',' or ')' in /var/www/holimana/public/index.php on line 38" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "POST /user/new HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080", referrer: "http://holimana.test:8080/user/new"
2018/08/30 12:21:43 [error] 7#7: *733 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected ';', expecting ',' or ')' in /var/www/holimana/public/index.php on line 38" while reading response header from upstream, client: 172.18.0.1, server: holimana.test, request: "GET /user/ HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "holimana.test:8080"
